// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veorhexddrwlwxtkuycb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlb3JoZXhkZHJ3bHd4dGt1eWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzM4NzUsImV4cCI6MjA2MTcwOTg3NX0.oXmev5TAFTvRC76BdsXgse3nra15fcxuJl2T610_K7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);